CONFIG_PRINTK=y

CONFIG_IPC_SERVICE=y
CONFIG_IPC_SERVICE_BACKEND_ICMSG=y
CONFIG_MBOX=y

CONFIG_LOG=y
CONFIG_ASSERT=y

# CONFIG_ARCH_LOG_LEVEL_DBG=y
CONFIG_SOC_LOG_LEVEL_DBG=y
# CONFIG_KERNEL_LOG_LEVEL_DBG=y
CONFIG_MBOX_LOG_LEVEL_DBG=y
CONFIG_IPM_LOG_LEVEL_DBG=y
CONFIG_IPC_SERVICE_LOG_LEVEL_DBG=y
# CONFIG_LOG_DEFAULT_LEVEL=4
# CONFIG_LOG_OVERRIDE_LEVEL=4


CONFIG_LOG_MODE_DEFERRED=y
# CONFIG_LOG_MODE_MINIMAL=y
CONFIG_LOG_BUFFER_SIZE=16384